# Dataframer: Fitzgerald's Odyssey to Pandas DF

### [—————————————pipeline—————————————]
### »——raw—»—clean—»—normalize—»—DATAFRAME——»

Here are some transformation and frequencies for future exploratory analysis of Green's Odyssey.

Columns: author, year, title, book_num, text, num_lines, num_sentences, num_words,

In [1]:
import numpy as np
import pandas as pd

import re
import nltk

import os

In [2]:
import sys
sys.path.append('/Users/debr/English-Homer') 
import bard_visualization as viz# This will apply the visualization settings

In [3]:
# TO UPDATE
translator = "Fitzgerald"

# Check Paths
filepath = f"/Users/debr/odysseys_en/Normalized_txts/Odyssey_{translator}_Normalized_v2.txt"
output_path = f"/Users/debr/English-Homer/dataframers_by_author/{translator}_EDA/"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
output_path_plots = f"{output_path}/plots/"
os.makedirs(os.path.dirname(output_path_plots), exist_ok=True)

# READING FILE TO extracted_lines
with open(filepath, 'r') as file:
    extracted_lines = file.readlines()

text = "".join(extracted_lines)

In [4]:
import re

def string_into_books(text, book_breaker):
    """
    Split a string into books/sections based on a pattern.
    
    Args:
        text (str): Text to process
        book_breaker (str): Pattern that indicates the start of a new book/section
    
    Returns:
        list: List of strings, where each string contains the content for one book/section
    """
    books = re.split(rf'{book_breaker}\s', text)
    # Remove the first element (it's empty or contains text before the first "Book")
    if books[0].strip() == "": 
        books = books[1:] #
        print(len(books))
    else:
        print("Warning: There was text before the first 'Book'")
    return books

def list_into_books(lines_list, book_breaker):
    
    """
    Split a list of strings into books/sections based on a pattern,
    excluding the lines that contain the book_breaker pattern.
    
    Args:
        lines_list (list): List of strings to process
        book_breaker (str): Pattern that indicates the start of a new book/section
    
    Returns:
        list: List of lists, where each inner list contains lines for one book/section
    """
    books = []
    current_book = []
    
    for line in lines_list:
        if line.strip().startswith(book_breaker):
            # If we already have content in current_book, save it and start a new one
            if current_book:
                books.append(current_book)
                current_book = []
            
            # Don't add the book_breaker line to the new book
            # Just start a new empty book
        else:
            # Add the line to the current book
            current_book.append(line)
    
    # Don't forget to add the last book if there's content
    if current_book:
        books.append(current_book)
    
    return books

# Example usage:
book_breaker = "BOOK"

#books = string_into_books(text, book_breaker)
books = list_into_books(extracted_lines, book_breaker)

# Verify the results
print(f"Found {len(books)} books")
for i, book in enumerate(books):
    print(f"Book {i+1} starts with: {book[0]}")
    print(f"Book {i+1} has {len(book)} lines")

Found 24 books
Book 1 starts with: Sing in me, Muse, and through me tell the story

Book 1 has 500 lines
Book 2 starts with: When primal Dawn spread on the eastern sky

Book 2 has 462 lines
Book 3 starts with: The sun rose on the flawless brimming sea

Book 3 has 542 lines
Book 4 starts with: By vales and sharp ravines in Lakedaimon

Book 4 has 901 lines
Book 5 starts with: Dawn came up from the couch of her reclining,

Book 5 has 519 lines
Book 6 starts with: Far gone in weariness, in oblivion,

Book 6 has 351 lines
Book 7 starts with: As Lord Odysseus prayed there in the grove

Book 7 has 371 lines
Book 8 starts with: Under the opening fingers of the dawn

Book 8 has 626 lines
Book 9 starts with: Now this was the reply Odysseus made:

Book 9 has 618 lines
Book 10 starts with: We made our landfall on Aiolia Island,

Book 10 has 635 lines
Book 11 starts with: We bore down on the ship at the sea’s edge

Book 11 has 759 lines
Book 12 starts with: The ship sailed on, out of the Ocean Stream,

Book 12 has 580 lines
Book 13 starts with: He ended it, and no one stirred or sighed

Book 13 has 551 lines
Book 14 starts with: He went up from the cove through wooded ground,

Book 14 has 631 lines
Book 15 starts with: South into Lakedaimon

Book 15 has 677 lines
Book 16 starts with: But there were two men in the mountain hut—

Book 16 has 592 lines
Book 17 starts with: When the young Dawn came bright into the East

Book 17 has 794 lines
Book 18 starts with: Now a true scavenger came in—a public tramp

Book 18 has 520 lines
Book 19 starts with: Now by Athena’s side in the quiet hall

Book 19 has 699 lines
Book 20 starts with: Outside in the entry way he made his bed—

Book 20 has 439 lines
Book 21 starts with: Upon Penelope, most worn in love and thought,

Book 21 has 500 lines
Book 22 starts with: Now shrugging off his rags the wiliest fighter of the islands leapt and

Book 22 has 566 lines
Book 23 starts with: The old nurse went upstairs exulting,

Book 23 has 422 lines
Book 24 starts with: Meanwhile the suitors’ ghosts were called away

Book 24 has 614 lines

In [5]:
# Dataframer
def odyssey_dataframer(author, year, title, list_books):
    """
    Splits a list_books into rows and creates a DataFrame.
    Args:
    list_books (list): The full text of the Odyssey
    author (str): Author name
    year (str): Publication year
    title (str): Book title
    Returns:
    pd.DataFrame: DataFrame with columns for author, year, title, book_num, and text
    """
    # Create a list to store the data for each book
    data = []
    
    # Loop through each book in the list
    for i, book_text in enumerate(list_books, 1):  # Start counting from 1
        # Add a row for this book
        data.append({
            'author': author,
            'year': year,
            'title': title,
            'book_num': i,
            'text': book_text
        })
    
    # Create the DataFrame from the data
    df = pd.DataFrame(data)
    
    return df


df = odyssey_dataframer(f"{translator}", "2018", "The Odyssey", books)
df

,author,year,title,book_num,text
0,Fitzgerald,2018,The Odyssey,1,"[Sing in me, Muse, and through me tell the sto..."
1,Fitzgerald,2018,The Odyssey,2,[When primal Dawn spread on the eastern sky \n...
2,Fitzgerald,2018,The Odyssey,3,"[The sun rose on the flawless brimming sea \n,..."
3,Fitzgerald,2018,The Odyssey,4,"[By vales and sharp ravines in Lakedaimon \n, ..."
4,Fitzgerald,2018,The Odyssey,5,"[Dawn came up from the couch of her reclining,..."
5,Fitzgerald,2018,The Odyssey,6,"[Far gone in weariness, in oblivion, \n, the n..."
6,Fitzgerald,2018,The Odyssey,7,[As Lord Odysseus prayed there in the grove \n...
7,Fitzgerald,2018,The Odyssey,8,"[Under the opening fingers of the dawn \n, Alk..."
8,Fitzgerald,2018,The Odyssey,9,"[Now this was the reply Odysseus made: \n, “Al..."
9,Fitzgerald,2018,The Odyssey,10,"[We made our landfall on Aiolia Island, \n, do..."
10,Fitzgerald,2018,The Odyssey,11,[We bore down on the ship at the sea’s edge \n...
11,Fitzgerald,2018,The Odyssey,12,"[The ship sailed on, out of the Ocean Stream, ..."
12,Fitzgerald,2018,The Odyssey,13,"[He ended it, and no one stirred or sighed \n,..."
13,Fitzgerald,2018,The Odyssey,14,[He went up from the cove through wooded groun...
14,Fitzgerald,2018,The Odyssey,15,"[South into Lakedaimon \n, into the land where..."
15,Fitzgerald,2018,The Odyssey,16,[But there were two men in the mountain hut— \...
16,Fitzgerald,2018,The Odyssey,17,[When the young Dawn came bright into the East...
17,Fitzgerald,2018,The Odyssey,18,[Now a true scavenger came in—a public tramp \...
18,Fitzgerald,2018,The Odyssey,19,"[Now by Athena’s side in the quiet hall \n, st..."
19,Fitzgerald,2018,The Odyssey,20,"[Outside in the entry way he made his bed— \n,..."
20,Fitzgerald,2018,The Odyssey,21,"[Upon Penelope, most worn in love and thought,..."
21,Fitzgerald,2018,The Odyssey,22,[Now shrugging off his rags the wiliest fighte...
22,Fitzgerald,2018,The Odyssey,23,"[The old nurse went upstairs exulting, \n, wit..."
23,Fitzgerald,2018,The Odyssey,24,[Meanwhile the suitors’ ghosts were called awa...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   author    24 non-null     object
 1   year      24 non-null     object
 2   title     24 non-null     object
 3   book_num  24 non-null     int64
 4   text      24 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.1+ KB

In [9]:
df['text'][0]

['Sing in me, Muse, and through me tell the story \n',
 'of that man skilled in all ways of contending, \n',
 'the wanderer, harried for years on end, \n',
 'after he plundered the stronghold \n',
 'on the proud height of Troy. \n',
 'He saw the townlands \n',
 'and learned the minds of many distant men, \n',
 'and weathered many bitter nights and days \n',
 'in his deep heart at sea, while he fought only \n',
 'to save his life, to bring his shipmates home. \n',
 'But not by will nor valor could he save them, \n',
 'for their own recklessness destroyed them all— \n',
 'children and fools, they killed and feasted on \n',
 'the cattle of Lord Helios, the Sun, \n',
 'and he who moves all day through heaven \n',
 'took from their eyes the dawn of their return. \n',
 'Of these adventures, Muse, daughter of Zeus, \n',
 'tell us in our time, lift the great song again. \n',
 'Begin when all the rest who left behind them \n',
 'headlong death in battle or at sea \n',
 'had long ago returned, while he alone still hungered \n',
 'for home and wife. Her ladyship Kalypso \n',
 'clung to him in her sea-hollowed caves— \n',
 'a nymph, immortal and most beautiful, \n',
 'who craved him for her own. \n',
 'And when long years and seasons \n',
 'wheeling brought around that point of time \n',
 'ordained for him to make his passage homeward, \n',
 'trials and dangers, even so, attended him \n',
 'even in Ithaka, near those he loved. \n',
 'Yet all the gods had pitied Lord Odysseus, \n',
 'all but Poseidon, raging cold and rough \n',
 'against the brave king till he came ashore \n',
 'at last on his own land. \n',
 'But now that god \n',
 'had gone far off among the sunburnt races, \n',
 'most remote of men, at earth’s two verges, \n',
 'in sunset lands and lands of the rising sun, \n',
 'to be regaled by smoke of thighbones burning, \n',
 'haunches of rams and bulls, a hundred fold. \n',
 'He lingered delighted at the banquet side. \n',
 'In the bright hall of Zeus upon Olympos \n',
 'the other gods were all at home, and Zeus, \n',
 'the father of gods and men, made conversation. \n',
 'For he had meditated on Aigisthos, dead \n',
 'by the hand of Agamemnon’s son, Orestes, \n',
 'and spoke his thought aloud before them all: \n',
 '“My word, how mortals take the gods to task! \n',
 'All their afflictions come from us, we hear. \n',
 'And what of their own failings? Greed and folly \n',
 'double the suffering in the lot of man. \n',
 'See how Aigisthos, for his double portion, \n',
 'stole Agamemnon’s wife and killed the soldier \n',
 'on his homecoming day. And yet Aigisthos \n',
 'knew that his own doom lay in this. We gods \n',
 'had warned him, sent down Hermes Argeiphontes, \n',
 'our most observant courier, to say: \n',
 '‘Don’t kill the man, don’t touch his wife, \n',
 'or face a reckoning with Orestes \n',
 'the day he comes of age and wants his patrimony.’ \n',
 'Friendly advice—but would Aigisthos take it? \n',
 'Now he has paid the reckoning in full.” \n',
 'The grey-eyed goddess Athena replied to Zeus: \n',
 '“O Majesty, O Father of us all, \n',
 'that man is in the dust indeed, and justly. \n',
 'So perish all who do what he had done. \n',
 'But my own heart is broken for Odysseus, \n',
 'the master mind of war, so long a castaway \n',
 'upon an island in the running sea; \n',
 'a wooded island, in the sea’s middle, \n',
 'and there’s a goddess in the place, the daughter \n',
 'of one whose baleful mind knows all the deeps \n',
 'of the blue sea—Atlas, who holds the columns \n',
 'that bear from land the great thrust of the sky. \n',
 'His daughter will not let Odysseus go, \n',
 'poor mournful man; she keeps on coaxing him \n',
 'with her beguiling talk, to turn his mind \n',
 'from Ithaka. But such desire is in him \n',
 'merely to see the hearthsmoke leaping upward \n',
 'from his own island, that he longs to die. \n',
 'Are you not moved by this, Lord of Olympos? \n',
 'Had you no pleasure from Odysseus’ offerings \n',
 'beside the Argive ships, on Troy’s wide seaboard? \n',
 'O Zeus, what do you hold against him now?” \n',
 'To this the summoner of cloud replied: \n',
 '“My child, what strange remarks you let escape you. \n',
 'Could I forget that kingly man, Odysseus? \n',
 'There is no mortal half so wise; no mortal \n',
 'gave so much to the lords of open sky. \n',
 'Only the god who laps the land in water, \n',
 'Poseidon, bears the fighter an old grudge \n',
 'since he poked out the eye of Polyphemos, \n',
 'brawniest of the Kyklopes. Who bore \n',
 'that giant lout? Thodsa, daughter of Phorkys, \n',
 'an offshore sea lord: for this nymph had lain \n',
 'with Lord Poseidon in her hollow caves. \n',
 'Naturally, the god, after the blinding— \n',
 'mind you, he does not kill the man; \n',
 'he only buffets him away from home. \n',
 'But come now, we are all at leisure here, \n',
 'let us take up this matter of his return, \n',
 'that he may sail. Poseidon must relent \n',
 'for being quarrelsome will get him nowhere, \n',
 'one god, flouting the will of all the gods.” \n',
 'The grey-eyed goddess Athena answered him: \n',
 '“O Majesty, O Father of us all, \n',
 'if it now please the blissful gods \n',
 'that wise Odysseus reach his home again, \n',
 'let the Wayfinder, Hermes, cross the sea \n',
 'to the island of Ogygia; let him tell \n',
 'our fixed intent to the nymph with pretty braids, \n',
 'and let the steadfast man depart for home. \n',
 'For my part, I shall visit Ithaka \n',
 'to put more courage in the son, and rouse him \n',
 'to call an assembly of the islanders, \n',
 'Akhaian gentlemen with flowing hair. \n',
 'He must warn off that wolf pack of the suitors \n',
 'who prey upon his flocks and dusky cattle. \n',
 'Pll send him to the mainland then, to Sparta \n',
 'by the sand beach of Pylos; let him find \n',
 'news of his dear father where he may \n',
 'and win his own renown about the world.” \n',
 'She bent to tie her beautiful sandals on, \n',
 'ambrosial, golden, that carry her over water \n',
 'or over endless land on the wings of the wind, \n',
 'and took the great haft of her spear in hand— \n',
 'that bronzeshod spear this child of Power can use \n',
 'to break in wrath long battle lines of fighters. \n',
 'Flashing down from Olympos’ height she went \n',
 'to stand in Ithaka, before the Manor, \n',
 'just at the doorsill of the court. She seemed \n',
 'a family friend, the Taphian captain, Mentes, \n',
 'waiting, with a light hand on her spear. \n',
 'Before her eyes she found the lusty suitors \n',
 'casting dice inside the gate, at ease \n',
 'on hides of oxen—oxen they had killed. \n',
 'Their own retainers made a busy sight \n',
 'with houseboys mixing bowls of water and wine, \n',
 'or sopping water up in sponges, wiping \n',
 'tables to be placed about in hall, \n',
 'or butchering whole carcasses for roasting. \n',
 'Long before anyone else, the prince Telemakhos \n',
 'now caught sight of Athena—for he, too, \n',
 'was sitting there unhappy among the suitors, \n',
 'a boy, daydreaming. What if his great father \n',
 'came from the unknown world and drove these men \n',
 'like dead leaves through the place, recovering \n',
 'honor and lordship in his own domains? \n',
 'Then he who dreamed in the crowd gazed out at Athena. \n',
 'Straight to the door he came, irked with himself \n',
 'to think a visitor had been kept there waiting, \n',
 'and took her right hand, grasping with his left \n',
 'her tall bronze-bladed spear. Then he said warmly: \n',
 '“Greetings, stranger! Welcome to our feast. \n',
 'There will be time to tell your errand later.” \n',
 'He led the way, and Pallas Athena followed \n',
 'into the lofty hall. The boy reached up \n',
 'and thrust her spear high in a polished rack \n',
 'against a pillar where tough spear on spear \n',
 'of the old soldier, his father, stood in order. \n',
 'Then, shaking out a splendid coverlet, \n',
 'he seated her on a throne with footrest—all \n',
 'finely carved—and drew his painted armchair \n',
 'near her, at a distance from the rest. \n',
 'To be amid the din, the suitors’ riot, \n',
 'would ruin his guest’s appetite, he thought, \n',
 'and he wished privacy to ask for news \n',
 'about his father, gone for years. \n',
 'A maid \n',
 'brought them a silver finger bowl and filled it \n',
 'out of a beautiful spouting golden jug, \n',
 'then drew a polished table to their side. \n',
 'The larder mistress with her tray came by \n',
 'and served them generously. A carver lifted \n',
 'cuts of each roast meat to put on trenchers \n',
 'before the two. He gave them cups of gold, \n',
 'and these the steward as he went his rounds \n',
 'filled and filled again. \n',
 'Now came the suitors, \n',
 'young bloods trooping in to their own seats \n',
 'on thrones or easy chairs. Attendants poured \n',
 'water over their fingers, while the maids \n',
 'piled baskets full of brown loaves near at hand, \n',
 'and houseboys brimmed the bowls with wine. \n',
 'Now they laid hands upon the ready feast \n',
 'and thought of nothing more. Not till desire \n',
 'for food and drink had left them were they mindful \n',
 'of dance and song, that are the grace of feasting. \n',
 'A herald gave a shapely cithern harp \n',
 'to Phemios, whom they compelled to sing— \n',
 'and what a storm he plucked upon the strings \n',
 'for prelude! High and clear the song arose. \n',
 'Telemakhos now spoke to grey-eyed Athena, \n',
 'his head bent close, so no one else might hear: \n',
 '“Dear guest, will this offend you, if I speak? \n',
 'It is easy for these men to like these things, \n',
 'harping and song; they have an easy life, \n',
 'scot free, eating the livestock of another— \n',
 'a man whose bones are rotting somewhere now, \n',
 'white in the rain on dark earth where they lie, \n',
 'or tumbling in the groundswell of the sea. \n',
 'If he returned, if these men ever saw him, \n',
 'faster legs they’d pray for, to a man, \n',
 'and not more wealth in handsome robes or gold. \n',
 'But he is lost; he came to grief and perished, \n',
 'and there’s no help for us in someone’s hoping \n',
 'he still may come; that sun has long gone down. \n',
 'But tell me now, and put it for me clearly— \n',
 'who are you? Where do you come from? Where’s your home \n',
 'and family? What kind of ship is yours, \n',
 'and what course brought you here? Who are your sailors? \n',
 'I don’t suppose you walked here on the sea. \n',
 'Another thing—this too I ought to know— \n',
 'is Ithaka new to you, or were you ever \n',
 'a guest here in the old days? Far and near \n',
 'friends knew this house; for he whose home it was \n',
 'had much acquaintance in the world.” \n',
 'To this \n',
 'the grey-eyed goddess answered: \n',
 '“As you ask, \n',
 'I can account most clearly for myself. \n',
 'Mentes I’m called, son of the veteran \n',
 'Ankhialos; I rule seafaring Taphos. \n',
 'I came by ship, with a ship’s company, \n',
 'sailing the winedark sea for ports of call \n',
 'on alien shores—to Temese, for copper, \n',
 'bringing bright bars of iron in exchange. \n',
 'My ship is moored on a wild strip of coast \n',
 'in Reithron Bight, under the wooded mountain. \n',
 'Years back, my family and yours were friends, \n',
 'as Lord Laertes knows; ask when you see him. \n',
 'I hear the old man comes to town no longer, \n',
 'stays up country, ailing, with only one \n',
 'old woman to prepare his meat and drink \n',
 'when pain and stiffness take him in the legs \n',
 'from working on his terraced plot, his vineyard. \n',
 'As for my sailing here— \n',
 'the tale was that your father had come home, \n',
 'therefore I came. I see the gods delay him. \n',
 'But never in this world is Odysseus dead— \n',
 'only detained somewhere on the wide sea, \n',
 'upon some island, with wild islanders; \n',
 'savages, they must be, to hold him captive. \n',
 'Well, I will forecast for you, as the gods \n',
 'put the strong feeling in me—I see it all, \n',
 'and I’m no prophet, no adept in bird-signs. \n',
 'He will not, now, be long away from Ithaka, \n',
 'his father’s dear land; though he be in chains \n',
 'he’ll scheme a way to come; he can do anything. \n',
 'But tell me this now, make it clear to me: \n',
 'You must be, by your looks, Odysseus’ boy? \n',
 'The way your head is shaped, the fine eyes—yes, \n',
 'how like him! We took meals like this together \n',
 'many a time, before he sailed for Troy \n',
 'with all the lords of Argos in the ships. \n',
 'I have not seen him since, nor has he seen me.” \n',
 'And thoughtfully Telemakhos replied: \n',
 '“Friend, let me put it in the plainest way. \n',
 'My mother says I am his son; I know not \n',
 'surely. Who has known his own engendering? \n',
 'I wish at least I had some happy man \n',
 'as father, growing old in his own house— \n',
 'but unknown death and silence are the fate \n',
 'of him that, since you ask, they call my father.” \n',
 'Then grey-eyed Athena said: \n',
 '“The gods decreed \n',
 'no lack of honor in this generation: \n',
 'such is the son Penelope bore in you. \n',
 'But tell me now, and make this clear to me: \n',
 'what gathering, what feast is this? Why here? \n',
 'A wedding? Revel? At the expense of all? \n',
 'Not that, I think. How arrogant they seem, \n',
 'these gluttons, making free here in your house! \n',
 'A sensible man would blush to be among them.” \n',
 'To this Telemakhos answered: \n',
 '“Friend, now that you ask about these matters, \n',
 'our house was always princely, a great house, \n',
 'as long as he of whom we speak remained here. \n',
 'But evil days the gods have brought upon it, \n',
 'making him vanish, as they have, so strangely. \n',
 'Were his death known, I could not feel such pain— \n',
 'if he had died of wounds in Trojan country \n',
 'or in the arms of friends, after the war. \n',
 'They would have made a tomb for him, the Akhaians, \n',
 'and I should have all honor as his son. \n',
 'Instead, the whirlwinds got him, and no glory. \n',
 'He’s gone, no sign, no word of him; and I inherit \n',
 'trouble and tears—and not for him alone, \n',
 'the gods have laid such other burdens on me. \n',
 'For now the lords of the islands, \n',
 'Doulikhion and Same, wooded Zakynthos, \n',
 'and rocky Ithaka’s young lords as well, \n',
 'are here courting my mother; and they use \n',
 'our house as if it were a house to plunder. \n',
 'Spurn them she dare not, though she hates that marriage, \n',
 'nor can she bring herself to choose among them. \n',
 'Meanwhile they eat their way through all we have, \n',
 'and when they will, they can demolish me.” \n',
 'Pallas Athena was disturbed, and said: \n',
 '“Ah, bitterly you need Odysseus, then! \n',
 'High time he came back to engage these upstarts. \n',
 'I wish we saw him standing helmeted \n',
 'there in the doorway, holding shield and spear, \n',
 'looking the way he did when I first knew him. \n',
 'That was at our house, where he drank and feasted \n',
 'after he left Ephyra, homeward bound \n',
 'from a visit to the son of Mermeris, Ilos. \n',
 'He took his fast ship down the gulf that time \n',
 'for a fatal drug to dip his arrows in \n',
 'and poison the bronze points; but young Ilos \n',
 'turned him away, fearing the gods’ wrath. \n',
 'My father gave it, for he loved him well. \n',
 'I wish these men could meet the man of those days! \n',
 'They’d know their fortune quickly: a cold bed. \n',
 'Aye! but it lies upon the gods’ great knees \n',
 'whether he can return and force a reckoning \n',
 'in his own house, or not. \n',
 'If I were you, \n',
 'I should take steps to make these men disperse. \n',
 'Listen, now, and attend to what I say: \n',
 'at daybreak call the islanders to assembly, \n',
 'and speak your will, and call the gods to witness: \n',
 'the suitors must go scattering to their homes. \n',
 'Then here’s a course for you, if you agree: \n',
 'get a sound craft afloat with twenty oars \n',
 'and go abroad for news of your lost father— \n',
 'perhaps a traveller’s tale, or rumored fame \n',
 'issued from Zeus abroad in the world of men. \n',
 'Talk to that noble sage at Pylos, Nestor, \n',
 'then go to Menelaos, the red-haired king \n',
 'at Sparta, last man home of all the Akhaians. \n',
 'If you should learn your father is alive \n',
 'and coming home, you could hold out a year. \n',
 'Or if you learn that he is dead and gone, \n',
 'then you can come back to your own dear country \n',
 'and raise a mound for him, and burn his gear, \n',
 'with all the funeral honors due the man, \n',
 'and give your mother to another husband. \n',
 'When you have done all this, or seen it done, \n',
 'it will be time to ponder \n',
 'concerning these contenders in your house— \n',
 'how you should kill them, outright or by guile. \n',
 'You need not bear this insolence of theirs, \n',
 'you are a child no longer. Have you heard \n',
 'what glory young Orestes won \n',
 'when he cut down that two-faced man, Aigisthos, \n',
 'for killing his illustrious father? \n',
 'Dear friend, you are tall and well set-up, I see; \n',
 'be brave—you, too—and men in times to come \n',
 'will speak of you respectfully. \n',
 'Now I must join my ship; \n',
 'my crew will grumble if I keep them waiting. \n',
 'Look to yourself; remember what I told you.” \n',
 'Telemakhos replied: \n',
 '“Friend, you have done me \n',
 'kindness, like a father to his son, \n',
 'and I shall not forget your counsel ever. \n',
 'You must get back to sea, I know, but come \n',
 'take a hot bath, and rest; accept a gift \n',
 'to make your heart lift up when you embark— \n',
 'some precious thing, and beautiful, from me, \n',
 'a keepsake, such as dear friends give their friends.” \n',
 'But the grey-eyed goddess Athena answered him: \n',
 '“Do not delay me, for I love the sea ways. \n',
 'As for the gift your heart is set on giving, \n',
 'let me accept it on my passage home, \n',
 'and you shall have a choice gift in exchange.” \n',
 'With this Athena left him \n',
 'as a bird rustles upward, off and gone. \n',
 'But as she went she put new spirit in him, \n',
 'a new dream of his father, clearer now, \n',
 'so that he marvelled to himself \n',
 'divining that a god had been his guest. \n',
 'Then godlike in his turn he joined the suitors. \n',
 'The famous minstrel still sang on before them, \n',
 'and they sat still and listened, while he sang \n',
 'that bitter song, the Homecoming of Akhaians— \n',
 'how by Athena’s will they fared from Troy; \n',
 'and in her high room careful Penelope, \n',
 'Ikarios’ daughter, heeded the holy song. \n',
 'She came, then, down the long stairs of her house, \n',
 'this beautiful lady, with two maids in train \n',
 'attending her as she approached the suitors; \n',
 'and near a pillar of the roof she paused, \n',
 'her shining veil drawn over across her cheeks, \n',
 'the two girls close to her and still, \n',
 'and through her tears spoke to the noble minstrel: \n',
 '“Phemios, other spells you know, high deeds \n',
 'of gods and heroes, as the poets tell them; \n',
 'let these men hear some other; let them sit \n',
 'silent and drink their wine. But sing no more \n',
 'this bitter tale that wears my heart away. \n',
 'It opens in me again the wound of longing \n',
 'for one incomparable, ever in my mind— \n',
 'his fame all Hellas knows, and midland Argos.” \n',
 'But Telemakhos intervened and said to her: \n',
 '“Mother, why do you grudge our own dear minstrel \n',
 'joy of song, wherever his thought may lead? \n',
 'Poets are not to blame, but Zeus who gives \n',
 'what fate he pleases to adventurous men. \n',
 'Here is no reason for reproof: to sing \n',
 'the news of the Danaans! Men like best \n',
 'a song that rings like morning on the ear. \n',
 'But you must nerve yourself and try to listen. \n',
 'Odysseus was not the only one at Troy \n',
 'never to know the day of his homecoming. \n',

In [8]:
# Counters: lines, sentences, and words
def count_lines(text):
    """Function to count lines in a text by the number of newline characters.

    Args:
        text (string): The text to count lines in.

    Returns:
        integer: The number of lines in the text.
    """
    if isinstance(text, float) and pd.isna(text):  # Check if it's a NaN value
        return 0
    if not isinstance(text, str):  # Check if it's not a string
        return 0
    return text.count('\n') + 1

def count_sentences(text):
    """Function to count sentences (using basic punctuation) in a text.

    Args:
        text (str): lines of the Odyssey 

    Returns:
        integer: number of sentences in the text
    """
    if isinstance(text, float) and pd.isna(text):
        return 0
    if not isinstance(text, str):
        return 0
    return len(re.findall(r'[.!?]+', text)) + 1  # Count sentence endings

def count_words(text):
    """Count the number of words in a text 
    
    Args:
        text (str): lines of the Odyssey
        
        Returns:
        integer: number of words in the text
    """
    if isinstance(text, float) and pd.isna(text):
        return 0
    if not isinstance(text, str):
        return 0
    return len(re.findall(r'\b\w+\b', text))

# Apply functions & add new columns
df['num_lines'] = df['text'].apply(count_lines)
df['num_sentences'] = df['text'].apply(count_sentences)
df['num_words'] = df['text'].apply(count_words)

df

,author,year,title,book_num,text,num_lines,num_sentences,num_words
0,Fitzgerald,2018,The Odyssey,1,"[Sing in me, Muse, and through me tell the sto...",0,0,0
1,Fitzgerald,2018,The Odyssey,2,[When primal Dawn spread on the eastern sky \n...,0,0,0
2,Fitzgerald,2018,The Odyssey,3,"[The sun rose on the flawless brimming sea \n,...",0,0,0
3,Fitzgerald,2018,The Odyssey,4,"[By vales and sharp ravines in Lakedaimon \n, ...",0,0,0
4,Fitzgerald,2018,The Odyssey,5,"[Dawn came up from the couch of her reclining,...",0,0,0
5,Fitzgerald,2018,The Odyssey,6,"[Far gone in weariness, in oblivion, \n, the n...",0,0,0
6,Fitzgerald,2018,The Odyssey,7,[As Lord Odysseus prayed there in the grove \n...,0,0,0
7,Fitzgerald,2018,The Odyssey,8,"[Under the opening fingers of the dawn \n, Alk...",0,0,0
8,Fitzgerald,2018,The Odyssey,9,"[Now this was the reply Odysseus made: \n, “Al...",0,0,0
9,Fitzgerald,2018,The Odyssey,10,"[We made our landfall on Aiolia Island, \n, do...",0,0,0
10,Fitzgerald,2018,The Odyssey,11,[We bore down on the ship at the sea’s edge \n...,0,0,0
11,Fitzgerald,2018,The Odyssey,12,"[The ship sailed on, out of the Ocean Stream, ...",0,0,0
12,Fitzgerald,2018,The Odyssey,13,"[He ended it, and no one stirred or sighed \n,...",0,0,0
13,Fitzgerald,2018,The Odyssey,14,[He went up from the cove through wooded groun...,0,0,0
14,Fitzgerald,2018,The Odyssey,15,"[South into Lakedaimon \n, into the land where...",0,0,0
15,Fitzgerald,2018,The Odyssey,16,[But there were two men in the mountain hut— \...,0,0,0
16,Fitzgerald,2018,The Odyssey,17,[When the young Dawn came bright into the East...,0,0,0
17,Fitzgerald,2018,The Odyssey,18,[Now a true scavenger came in—a public tramp \...,0,0,0
18,Fitzgerald,2018,The Odyssey,19,"[Now by Athena’s side in the quiet hall \n, st...",0,0,0
19,Fitzgerald,2018,The Odyssey,20,"[Outside in the entry way he made his bed— \n,...",0,0,0
20,Fitzgerald,2018,The Odyssey,21,"[Upon Penelope, most worn in love and thought,...",0,0,0
21,Fitzgerald,2018,The Odyssey,22,[Now shrugging off his rags the wiliest fighte...,0,0,0
22,Fitzgerald,2018,The Odyssey,23,"[The old nurse went upstairs exulting, \n, wit...",0,0,0
23,Fitzgerald,2018,The Odyssey,24,[Meanwhile the suitors’ ghosts were called awa...,0,0,0

In [ ]:
# Group by book_num and count the number of sentences in each book
sentences_per_book = df.groupby('book_num')['num_sentences'].sum()

# Create the plot using predefined styles
fig, ax = plt.subplots(figsize=(14, 7))

# Use predefined color cycle from viz.COLORS
ax.bar(sentences_per_book.index, sentences_per_book.values)  # Use 'orange'

ax.set_xlabel('Book Number')
ax.set_ylabel('Number of Sentences')
ax.set_title(f"Sentence Frequency by Book in {translator}'s Odyssey")

# Ensure all book numbers are shown on the x-axis
ax.set_xticks(sentences_per_book.index)

# Grid styling from viz
ax.grid(axis='y', alpha=0.5)
# Add values on top of bars
for i, v in enumerate(sentences_per_book.values):
    ax.text(i + 1, v + 5, str(v), ha='center', fontsize=10, color='black')

# Apply tight layout
plt.tight_layout()

# Save the figure using the predefined function
viz.save_figure(fig, f"/Users/debr/English-Homer/dataframers_by_author/plots/{translator}-sentence_freq.png")

In [ ]:
# Group by book_num and count the number of lines in each book
lines_per_book = df.groupby('book_num')['num_lines'].sum()

# Create the plot using predefined styles
fig, ax = plt.subplots(figsize=(14, 7))

# Use predefined color cycle from viz.COLORS
ax.bar(lines_per_book.index, lines_per_book.values, color='#641B5E')  # Use 'orange'

ax.set_xlabel('Book Number')
ax.set_ylabel('Number of Lines')
ax.set_title(f"Line Frequency by Book in {translator}'s Odyssey")

# Ensure all book numbers are shown on the x-axis
ax.set_xticks(lines_per_book.index)

# Grid styling from viz
ax.grid(axis='y', alpha=0.5)
# Add values on top of bars
for i, v in enumerate(lines_per_book.values):
    ax.text(i + 1, v + 5, str(v), ha='center', fontsize=10, color='black')

# Apply tight layout
plt.tight_layout()

# Save the figure using the predefined function
viz.save_figure(fig, f"/Users/debr/English-Homer/dataframers_by_author/plots/{translator}-lines_freq.png")

In [ ]:
# Group by book_num and count the number of words in each book
words_per_book = df.groupby('book_num')['num_words'].sum()

# Create the plot using predefined styles
fig, ax = plt.subplots(figsize=(14, 7))

# Use predefined color cycle from viz.COLORS
ax.bar(words_per_book.index, words_per_book.values, color='#177070')  # Use 'orange'

ax.set_xlabel('Book Number')
ax.set_ylabel('Number of Words')
ax.set_title(f"Words Frequency by Book in {translator}'s Odyssey")

# Ensure all book numbers are shown on the x-axis
ax.set_xticks(words_per_book.index)

# Grid styling from viz
ax.grid(axis='y', alpha=0.5)
# Add values on top of bars
for i, v in enumerate(words_per_book.values):
    ax.text(i + 1, v + 5, str(v), ha='center', fontsize=10, color='black')

# Apply tight layout
plt.tight_layout()

# Save the figure using the predefined function
viz.save_figure(fig, f"/Users/debr/English-Homer/dataframers_by_author/plots/{translator}-words_freq_bB.png")

In [ ]:
books_first_lines = {
    'Book 1': 'The man, Muse—tell me about that resourceful man, who wandered',
    'Book 2': 'When Dawn appeared, early risen and rosy-fingered,',
    'Book 3': "Deserting the deep’s enchanting surface, the sun rose up",
    'Book 4': 'Now they came to deep-hollowed Lakedaimon with its ravines',
    'Book 5': 'As Dawn arose from her bed beside illustrious Tithonos,',
    'Book 6': 'So Odysseus slept on there, godlike and much-enduring,',
    'Book 7': 'So while Odysseus prayed there, godlike and much-enduring,',
    'Book 8': 'When Dawn appeared, early risen and rosy-fingered,',
    'Book 9': 'Then resourceful Odysseus responded to him, saying:',
    'Book 10': '“To the isle of Aiolia then we came, where was the dwelling',
    'Book 11': '“But when we came down to the ship and the sea, first off',
    'Book 12': '“After our ship left the course of Ocean’s river and came',
    'Book 13': 'So he spoke: every one of them sat hushed and silent,',
    'Book 14': 'But the rough path up from the harbor was that which Odysseus',
    'Book 15': 'Now Pallas Athene was gone to spacious Lakedaimon,',
    'Book 16': 'The two in the hut, Odysseus and the noble swineherd,',
    'Book 17': 'When Dawn appeared, early risen and rosy-fingered,',
    'Book 18': 'Now there came up a public beggar, whose custom it was to beg',
    'Book 19': 'So noble Odysseus was left behind, there in the hall,',
    'Book 20': 'But noble Odysseus bedded down for sleep in the forecourt.',
    'Book 21': 'The goddess, grey-eyed Athene, now put it into the mind',
    'Book 22': 'Now resourceful Odysseus stripped himself of his rags',
    'Book 23': 'Chuckling, the old woman ascended to the upper chamber,',
    'Book 24': 'Hermes, god of Kyllene, now summoned forth the ghosts'
}

In [ ]:
# Create output directory if it doesn't exist
output_filepath = f"/Users/debr/odysseys_en/Odyssey_dfs/Odyssey_{translator}_eda.csv"
os.makedirs(os.path.dirname(output_filepath), exist_ok=True)

# save df to csv
df.to_csv(output_filepath, index=False)